server:
  port: 3355

spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #服务注册进nacos

info:
  name: config-server
  version: 1.0

management:
  endpoints:
    web:
      exposure:
        include: "refresh"