server:
  port: 8002

spring:
  application:
    name: provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis01?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 20
      max-active: 100
  cloud:
    zookeeper: #zookeeper配置
      connect-string: 192.168.1.131:2181 #集群配置多个地址，中间用逗号分隔

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiaohu.model
  global-config:
    db-config:
      table-prefix:
      id-type: auto
  configuration:
  # 是否将sql打印到控制面板(该配置会将sql语句和查询的结果都打印到控制台)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #不启用日志
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

#actuator配置

#配置actuator的info信息
#访问方式：/actuator/info
#{"name":"hh","version":91}
info:
  name: provider1
  version: 1.0

management:
  endpoint:
    health:
      show-details: always #启用health端点详细信息，就能看到MyHealth自定义的健康信息