server:
  port: 9001


spring:
  application:
    name: consumer
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis01?useUnicode=true&characterEncoding=UTF-8&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: root
    druid:
      initial-size: 20
      max-active: 100
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xiaohu.model
  global-config:
    db-config:
      table-prefix:
      id-type: auto
  configuration:
    # 是否将sql打印到控制面板(该配置会将sql语句和查询的结果都打印到控制台)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #不启用日志
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl


#actuator配置
info:
  name: consumer1
  version: 1.0

management:
  #  server:
  #    port: 18081 #配置actuator的端口号，默认和应用公用一个端口
  endpoint:
    health:
      show-details: always #启用health端点详细信息，就能看到MyHealth自定义的健康信息
#  endpoints:
#    web:
#      base-path: /check #修改actuator访问path (不建议配置这个属性，因为其他eureka配置监测的这个路径固定写死的，改不了actuatorPrefix = "/actuator"）

rest:
  url:
#    provider: localhost:8001
#    provider: http://localhost:8001
    provider: http://provider