server:
  port: 9998

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
        client-ip: localhost
    gateway:
      discovery:
        locator:
          enabled: true #
      routes:
        - id: provider1 #路由的id，没固定规则，但要求唯一，建议配合服务名使用
#          uri: http://localhost:8001 #predicates匹配后提供服务的路由地址
          uri: lb://provider #开启从注册中心，动态创建路由的功能，利用微服务名进行路由
          predicates: #断言，路径相匹配的进行路由
            - Path=/provider/getPort/**
        - id: provider2
#          uri: http://localhost:8002
          uri: lb://provider
          predicates:
            - Path=/provider/getMessage/**


#Feign也是通过ribbon实现负载均衡。配置ribbon设置连接超时时间和读取超时时间
ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 2000
#定制服务日志级别（打印出Feign调用详细日志）（配合FeignLoggerConfig使用）
#logging:
#  level:
#    #    root: info
#    root: debug
    #    com.xiaohu.consumer.service.MyFirstFeignService: debug
#    com.xiaohu.consumer.service: debug


#actuator配置

#配置actuator的info信息
#访问方式：/actuator/info
#{"name":"hh","version":91}
info:
  name: provider1
  version: 1.0

management:
  endpoint:
    health:
      show-details: always #启用health端点详细信息，就能看到MyHealth自定义的健康信息

