server:
  port: 3344

spring:
  application:
    name: config-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #服务注册进nacos
    config:
      server:
        git:
          uri: git@github.com:xiaohuabc/microservice2.git #git项目地址
          search-paths:
            - config-server/src/main/resources/service-config #项目下，配置文件所在目录地址
          default-label: master #这个是服务端配置，如果请求配置的路径中不写分支，默认这里指定。
            #（如：http://localhost:3344/master/provider-master.yml 里面master可以不写）
#      label: master #这个配置应该是客户端，指定配置中心服务端的分支
# rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh" #开启bus总线刷新端点

info:
  name: config-server
  version: 1.0