server:
  port: 3344

spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    config:
      server:
        git:
          uri: git@github.com:xiaohuabc/microservice2.git
          search-paths:
            - config-server/src/main/resources/service-config
      label: master


#  cloud:
#    config:
#      server:
#        git:
#            uri:  填写你自己的github路径
#          search-paths:
#              - springcloud-config
#        label: master
info:
  name: provider1
  version: 1.0