server:
  port: 3344

spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    config:
      server:
        git:
          uri: git@github.com:xiaohuabc/microservice2.git
          search-paths:
            - config-server/src/main/resources/service-config
          default-label: dev #这个是服务端配置，如果请求配置的路径中不写分支，默认这里指定。
            #（如：http://localhost:3344/master/provider-master.yml 里面master可以不写）
#      label: dev #这个配置应该是客户端，指定配置中心服务端的分支


#  cloud:
#    config:
#      server:
#        git:
#            uri:  填写你自己的github路径
#          search-paths:
#              - springcloud-config
#        label: master
info:
  name: provider1
  version: 1.0